### ISSUE TITLE
If example contains `null` the whole resolver breaks and errors out as there is no null check in `handleCircularReferences`

### ISSUE THREAD

**Issue by ThaDaVos** [Rhosys/openapi-resolver.js#2] opened 2022-08-08 14:59 UTC
### Q&A (please complete the following information)
 - OS: [e.g. macOS] Windows
 - Environment: [e.g. Chrome 59, Node.js v10.0.0] Firefox 104
 - Method of installation: [e.g. npm, unpkg] npm
 - OpenAPI Resolver version: [e.g. 3.8.0] latest
 - OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0, OpenAPI 3.1] OpenAPI 3.0

### Content & configuration

OpenAPI definition:
```yaml
# Can't share
```

OpenAPI Resolver usage:
```js
openApiResolver({
  // Not used
})
```

### To reproduce...

1. Have an example in your OpenAPI docs which contains a null value, in our case it's for the `deleted_at` column
2. Try loading it with OpenAPI Explorer, debug the whole day, figure out it's inside this package and find the root cause

### Expected behavior

It should just parse

### Additional context or thoughts

The error is caused on the following line:
https://github.com/Rhosys/openapi-resolver.js/blob/f16c6e828948f3af44b7956dee7c48bbc5b2202b/src/index.js#L15

For some reason its also parsing the example object, which in our case contains a `deleted_at: null` - this results in the above line to error out as there is a `null` being passed in and because Javascript is weird: `typeof null === "object"`
![image](https://user-images.githubusercontent.com/5251028/183448546-272950df-b19a-4acc-bf0b-fbf60c2bfe99.png)

**Comment by wparad** [comment] 2022-08-08 15:19
Can you provide a minimal repo spec, so we can investigate?

**Comment by wparad** [comment] 2022-08-08 15:20
Alternatively if you already know what the problem is a PR would be greatly appreciated!

**Comment by ThaDaVos** [comment] 2022-08-08 15:59
The exact error seems to be on the given line: https://github.com/Rhosys/openapi-resolver.js/blob/f16c6e828948f3af44b7956dee7c48bbc5b2202b/src/index.js#L15

As the check above it doesn't check for `null` itself and `null` is an object according to JavaScript - I can give a PR - give me a few secs

**Comment by wparad** [comment] 2022-08-08 16:04
Got it, i think a `!objectWithRef ||` in the proceeding if statement is likely the fix

**Comment by ThaDaVos** [comment] 2022-08-08 16:06
I made the PR - I added it as and extra IF statement so we can return `null` - for example, in my case it crashed because my example contained `deleted_at: null` - this I would like to keep as `null` and not turn into a `undefined` as that's not what my API will be returning

#<3GithubWorkspaces - made this a really quick edit

**Comment by ThaDaVos** [comment] 2022-08-08 16:07
Also, you don't need the check for `undefined` as `typeof undefined === "undefined"`

**Comment by wparad** [comment] 2022-08-08 16:11
That's actually not how undefined works :). `undefined` means delegate the handling of this back to the caller instead of explicitly handling it.  That's why I made that recommendation since this is more consistent with the expectations of the function handling. 

But we can go with this, although it might be confusing with future reviewers.

**Comment by ThaDaVos** [comment] 2022-08-08 16:18
Oh thanks for the explanation: quick question, when can we expect this to be released so openapi-explorer can also be used again? Because that's where I found out it was broken in the first place 😂

**Comment by wparad** [comment] 2022-08-08 16:19
That's why I switched the PR to the `release/4.0` branch. `4.0.30` should already be available.

**Comment by ThaDaVos** [comment] 2022-08-09 14:57
Does https://github.com/Rhosys/openapi-explorer use `4.0.30` also? I just checked and I am still getting the error

**Comment by ThaDaVos** [comment] 2022-08-09 15:01
Checking the decompiled code, it doesn't seem to be:
![image](https://user-images.githubusercontent.com/5251028/183685519-6853706b-9331-4659-8549-7f9268f30fb2.png)

**Comment by wparad** [comment] 2022-08-09 15:42
Not unless someone created/merged an update. The easiest way to check is look at the package.json. in general the library isn't pinned to specific versions, but if you are using the the prepackaged version, nothing would he told it to recompile.

**Closed as completed by wparad** 2022-08-09 15:42 UTC

**Comment by wparad** [comment] 2022-08-09 17:20
The non compiled version now has a flexible package version for this resolver. Hopefully that solves your issue https://github.com/Rhosys/openapi-explorer/pull/80 otherwise, I would appreciate knowing better your need to use the compiled version of the library. Of course if it is really required upgrading the compiled package can be done as well, but I'm assuming this will be sufficient.

**Comment by ThaDaVos** [comment] 2022-08-09 17:45
Yeah I used the prepackaged version -> `node_modules/openapi-explorer/dist/browser/openapi-explorer.min.js` (if I remember correctly of the top of my head)

**Comment by wparad** [comment] 2022-08-16 14:48
Ah that explains it, they'll need to an update to the explorer to use the new version. I'm actually away from computer this week, so as soon I get back, I can roll the version there (or feel free to make a PR in that repo and I can approve/merge it in)
